version: "3"

services:
   db:
      container_name: mysql
      image: mysql:5.7
      volumes:
         - wp_db:
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: somewordpress
         MYSQL_DATABASE: wordpress
         MYSQL_USER: wordpress
         MYSQL_PASSWORD: wordpress
      networks:
         - wp
         
   wordpress:
     depends_on:
        - db
     container_name: wordpress
     image: wordpress:latest
     volumes:
        - wp_statics:
     ports:
        - "8000:80"
     restart: always
     environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
     networks:
        - wp
        
   phpmyadmin:
     depends_on:
        - db
     container_name: phpmyadmin
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
        - 7777:80
     environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: password
     networks:
        - wp
  
        
networks:
  wp:
  webgateway:
     driver: bridge
     
volumes:
   wp_db:
   wp_statics:
        
